spring.application.name=sb-ecom

#------MySQL DB-----------------
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=734758@nN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#--------------------------------

#------H2 DB-----------------
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
#--------------------------------

project.image = images/

spring.app.jwtSecret=mySecretKey123912738sdsdasd56523321dsfs32f1s5ew32e13s2xf15w1efw21f32s1ajsdkajshdkajshd
spring.app.jwtExpirationMs=300000
spring.ecom.app.jwtCookieName=springBootEcom

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG